/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package ssfzxc.json.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int SPACES = 1;
    /**
     * RegularExpression Id.
     */
    int NUMBER = 2;
    /**
     * RegularExpression Id.
     */
    int STRING = 6;
    /**
     * RegularExpression Id.
     */
    int TRUE = 7;
    /**
     * RegularExpression Id.
     */
    int FALSE = 8;
    /**
     * RegularExpression Id.
     */
    int NULL = 9;
    /**
     * RegularExpression Id.
     */
    int OBJECT_BEGIN = 10;
    /**
     * RegularExpression Id.
     */
    int OBJECT_END = 11;
    /**
     * RegularExpression Id.
     */
    int ARRAY_BEGIN = 12;
    /**
     * RegularExpression Id.
     */
    int ARRAY_END = 13;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;
    /**
     * Lexical state.
     */
    int IN_STRING = 1;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
        "<EOF>",
        "<SPACES>",
        "<NUMBER>",
        "\"\\\"\"",
        "<token of kind 4>",
        "<token of kind 5>",
        "\"\\\"\"",
        "\"true\"",
        "\"false\"",
        "\"null\"",
        "\"{\"",
        "\"}\"",
        "\"[\"",
        "\"]\"",
        "\":\"",
        "\",\"",
    };

}
